/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.mycompany.petagenda.MenuPanel;
import javax.swing.JScrollPane;
import petagenda.dados.Porte;
import petagenda.dados.Sexo;
import ui.custom.RoundedCornerBorder;
import ui.custom.RoundedCornerButtonUI;

/**
 *
 * @author kevin
 */
public class tela_atualizar_pet extends javax.swing.JFrame {

    /**
     * Creates new form tela_atualizar_pet
     */
    public tela_atualizar_pet() {
        initComponents();
        initMenuPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_atualizar_pet = new javax.swing.JPanel();
        jlbl_atualizar_pet = new javax.swing.JLabel();
        jlbl_nome_pet = new javax.swing.JLabel();
        JTxtF_nome_pet = new javax.swing.JTextField();
        jlbl_nome_dono = new javax.swing.JLabel();
        JTxtF_nome_dono = new javax.swing.JTextField();
        jlbl_castrado = new javax.swing.JLabel();
        chkBx_Sim = new javax.swing.JCheckBox("Sim");
        chkBx_Nao = new javax.swing.JCheckBox("Não");
        jllb_vacinas = new javax.swing.JLabel();
        jbtn_AddVacinas = new javax.swing.JButton();
        jlbl_raca = new javax.swing.JLabel();
        JTxtF_raca = new javax.swing.JTextField();
        jlbl_porte = new javax.swing.JLabel();
        jcmbBx_Porte = new javax.swing.JComboBox<Porte>(Porte.values());
        jlbl_cor = new javax.swing.JLabel();
        JTxtF_cor = new javax.swing.JTextField();
        jlbl_sexo = new javax.swing.JLabel();
        jcmbBx_sexo = new javax.swing.JComboBox<>(Sexo.values());
        jtextArea_compor_pet = new javax.swing.JLabel();
        jtxtArea_Comportamento = new javax.swing.JScrollPane();
        jtxtarea_comportamento = new javax.swing.JTextArea();
        jtextArea_saude_pet = new javax.swing.JLabel();
        jtxtArea_Saude = new javax.swing.JScrollPane();
        jtxtarea_saude = new javax.swing.JTextArea();
        jbtn_atualizarPet = new javax.swing.JButton();
        jPanel_menu = new javax.swing.JPanel();
        jlbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_atualizar_pet.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_atualizar_pet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jpanel_atualizar_pet.setPreferredSize(new java.awt.Dimension(899, 617));
        jpanel_atualizar_pet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_atualizar_pet.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
        jlbl_atualizar_pet.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_atualizar_pet.setText("Atualizar pet");
        jpanel_atualizar_pet.add(jlbl_atualizar_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jlbl_nome_pet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_nome_pet.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nome_pet.setText("Nome do pet:");
        jpanel_atualizar_pet.add(jlbl_nome_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 84, -1, -1));

        JTxtF_nome_pet.setBackground(new java.awt.Color(217, 217, 217));
        JTxtF_nome_pet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JTxtF_nome_pet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JTxtF_nome_pet.setMinimumSize(new java.awt.Dimension(250, 50));
        JTxtF_nome_pet.setPreferredSize(new java.awt.Dimension(250, 50));
        JTxtF_nome_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtF_nome_petActionPerformed(evt);
            }
        });
        jpanel_atualizar_pet.add(JTxtF_nome_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 103, -1, -1));

        jlbl_nome_dono.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_nome_dono.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nome_dono.setText("Nome do dono:");
        jpanel_atualizar_pet.add(jlbl_nome_dono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 84, -1, -1));

        JTxtF_nome_dono.setBackground(new java.awt.Color(217, 217, 217));
        JTxtF_nome_dono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JTxtF_nome_dono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JTxtF_nome_dono.setMinimumSize(new java.awt.Dimension(250, 50));
        JTxtF_nome_dono.setPreferredSize(new java.awt.Dimension(250, 50));
        JTxtF_nome_dono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtF_nome_donoActionPerformed(evt);
            }
        });
        jpanel_atualizar_pet.add(JTxtF_nome_dono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 103, -1, -1));

        jlbl_castrado.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_castrado.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_castrado.setText("Castrado:");
        jpanel_atualizar_pet.add(jlbl_castrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        chkBx_Sim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                // Verifica se o JCheckBox "Sim" foi selecionado
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    // Se "Sim" for selecionado, desmarque "Não"
                    chkBx_Nao.setSelected(false);
                }
            }
        });
        chkBx_Sim.setBackground(new java.awt.Color(255, 255, 255));
        chkBx_Sim.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        chkBx_Sim.setForeground(new java.awt.Color(0, 0, 0));
        chkBx_Sim.setText("SIM");
        chkBx_Sim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        chkBx_Sim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkBx_Sim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBx_SimStateChanged(evt);
            }
        });
        chkBx_Sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_SimActionPerformed(evt);
            }
        });
        jpanel_atualizar_pet.add(chkBx_Sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        chkBx_Nao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                // Verifica se o JCheckBox "Não" foi selecionado
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    // Se "Não" for selecionado, desmarque "Sim"
                    chkBx_Sim.setSelected(false);
                }
            }
        });
        chkBx_Nao.setBackground(new java.awt.Color(255, 255, 255));
        chkBx_Nao.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        chkBx_Nao.setForeground(new java.awt.Color(0, 0, 0));
        chkBx_Nao.setText("NÃO");
        chkBx_Nao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        chkBx_Nao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_atualizar_pet.add(chkBx_Nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        jllb_vacinas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jllb_vacinas.setForeground(new java.awt.Color(0, 0, 0));
        jllb_vacinas.setText("Vacinas:");
        jpanel_atualizar_pet.add(jllb_vacinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jbtn_AddVacinas.setBackground(new java.awt.Color(217, 217, 217));
        jbtn_AddVacinas.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jbtn_AddVacinas.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_AddVacinas.setText("ADICIONAR");
        jbtn_AddVacinas.setBorder(new RoundedCornerBorder(16));
        jbtn_AddVacinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_AddVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AddVacinasActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_atualizarPet.setUI(new RoundedCornerButtonUI());
        jpanel_atualizar_pet.add(jbtn_AddVacinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 122, 19));

        jlbl_raca.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_raca.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_raca.setText("Raça:");
        jpanel_atualizar_pet.add(jlbl_raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 179, -1, -1));

        JTxtF_raca.setBackground(new java.awt.Color(217, 217, 217));
        JTxtF_raca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JTxtF_raca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JTxtF_raca.setMinimumSize(new java.awt.Dimension(240, 50));
        JTxtF_raca.setPreferredSize(new java.awt.Dimension(240, 50));
        JTxtF_raca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtF_racaActionPerformed(evt);
            }
        });
        jpanel_atualizar_pet.add(JTxtF_raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jlbl_porte.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_porte.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_porte.setText("Porte:");
        jpanel_atualizar_pet.add(jlbl_porte, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jcmbBx_Porte.setBackground(new java.awt.Color(217, 217, 217));
        jcmbBx_Porte.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jcmbBx_Porte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcmbBx_Porte.setMinimumSize(new java.awt.Dimension(232, 50));
        jcmbBx_Porte.setPreferredSize(new java.awt.Dimension(232, 50));
        jcmbBx_Porte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbBx_PorteActionPerformed(evt);
            }
        });
        jpanel_atualizar_pet.add(jcmbBx_Porte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 170, -1));

        jlbl_cor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_cor.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cor.setText("Cor:");
        jpanel_atualizar_pet.add(jlbl_cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        JTxtF_cor.setBackground(new java.awt.Color(217, 217, 217));
        JTxtF_cor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JTxtF_cor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JTxtF_cor.setMinimumSize(new java.awt.Dimension(240, 50));
        JTxtF_cor.setPreferredSize(new java.awt.Dimension(190, 50));
        JTxtF_cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtF_corActionPerformed(evt);
            }
        });
        jpanel_atualizar_pet.add(JTxtF_cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jlbl_sexo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jlbl_sexo.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_sexo.setText("Sexo:");
        jpanel_atualizar_pet.add(jlbl_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        for (Sexo sexo : Sexo.values()) {
            sexo.setTipoExibicao("PET");
        }
        jcmbBx_sexo.setBackground(new java.awt.Color(217, 217, 217));
        jcmbBx_sexo.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jcmbBx_sexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcmbBx_sexo.setMinimumSize(new java.awt.Dimension(232, 50));
        jcmbBx_sexo.setPreferredSize(new java.awt.Dimension(232, 50));
        jcmbBx_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbBx_sexoActionPerformed(evt);
            }
        });
        jpanel_atualizar_pet.add(jcmbBx_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 201, 140, -1));

        jtextArea_compor_pet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jtextArea_compor_pet.setForeground(new java.awt.Color(0, 0, 0));
        jtextArea_compor_pet.setText("Comportamento do pet:");
        jpanel_atualizar_pet.add(jtextArea_compor_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 279, -1, -1));

        jtxtArea_Comportamento.setBackground(new java.awt.Color(217, 217, 217));
        jtxtArea_Comportamento.setBorder(null);
        jtxtArea_Comportamento.setMinimumSize(new java.awt.Dimension(800, 80));
        jtxtArea_Comportamento.setPreferredSize(new java.awt.Dimension(800, 80));
        jtxtArea_Comportamento.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jtxtArea_Comportamento.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        jtxtarea_comportamento.setBackground(new java.awt.Color(217, 217, 217));
        jtxtarea_comportamento.setColumns(20);
        jtxtarea_comportamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtarea_comportamento.setRows(0);
        jtxtarea_comportamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtarea_comportamento.setOpaque(false);
        jtxtarea_comportamento.setPreferredSize(null);
        jtxtArea_Comportamento.setViewportView(jtxtarea_comportamento);

        jpanel_atualizar_pet.add(jtxtArea_Comportamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jtextArea_saude_pet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jtextArea_saude_pet.setForeground(new java.awt.Color(0, 0, 0));
        jtextArea_saude_pet.setText("Saúde do pet:");
        jpanel_atualizar_pet.add(jtextArea_saude_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 389, -1, -1));

        jtxtArea_Saude.setBackground(new java.awt.Color(217, 217, 217));
        jtxtArea_Saude.setBorder(null);
        jtxtArea_Saude.setMinimumSize(new java.awt.Dimension(800, 80));
        jtxtArea_Saude.setPreferredSize(new java.awt.Dimension(800, 80));
        jtxtArea_Saude.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jtxtArea_Saude.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        jtxtarea_saude.setBackground(new java.awt.Color(217, 217, 217));
        jtxtarea_saude.setColumns(20);
        jtxtarea_saude.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtarea_saude.setRows(0);
        jtxtarea_saude.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtarea_saude.setOpaque(false);
        jtxtarea_saude.setPreferredSize(null);
        jtxtArea_Saude.setViewportView(jtxtarea_saude);

        jpanel_atualizar_pet.add(jtxtArea_Saude, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 409, -1, -1));

        jbtn_atualizarPet.setBackground(new java.awt.Color(77, 120, 63));
        jbtn_atualizarPet.setFont(new java.awt.Font("Merriweather", 0, 20)); // NOI18N
        jbtn_atualizarPet.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_atualizarPet.setText("ATUALIZAR");
        jbtn_atualizarPet.setBorder(null);
        jbtn_atualizarPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_atualizarPet.setPreferredSize(new java.awt.Dimension(240, 50));
        jbtn_atualizarPet.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtn_atualizarPetMouseMoved(evt);
            }
        });
        jbtn_atualizarPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_atualizarPetMouseExited(evt);
            }
        });
        jbtn_atualizarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atualizarPetActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_atualizarPet.setUI(new RoundedCornerButtonUI());
        jpanel_atualizar_pet.add(jbtn_atualizarPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 240, 50));

        getContentPane().add(jpanel_atualizar_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 41, -1, -1));

        jPanel_menu.setBackground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setForeground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jPanel_menu.setMinimumSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));

        jlbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_PADRAO.png"))); // NOI18N
        jlbl_background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jlbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtF_corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtF_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtF_corActionPerformed

    private void JTxtF_nome_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtF_nome_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtF_nome_petActionPerformed

    private void JTxtF_nome_donoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtF_nome_donoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtF_nome_donoActionPerformed

    private void JTxtF_racaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtF_racaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtF_racaActionPerformed

    private void jcmbBx_PorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbBx_PorteActionPerformed
        // TODO add your handling code here:
        Porte selectedPorte = (Porte) jcmbBx_Porte.getSelectedItem();

    }//GEN-LAST:event_jcmbBx_PorteActionPerformed

    private void jcmbBx_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbBx_sexoActionPerformed
        // TODO add your handling code here:
        Sexo sexoSelecionado = (Sexo) jcmbBx_sexo.getSelectedItem();

        // Ação com base na seleção (aqui você vai usar PET, já que é para Pet)
        String sexoPet = sexoSelecionado.PET;
    }//GEN-LAST:event_jcmbBx_sexoActionPerformed

    private void chkBx_SimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBx_SimStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBx_SimStateChanged

    private void chkBx_SimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_SimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBx_SimActionPerformed

    private void jbtn_AddVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AddVacinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_AddVacinasActionPerformed

    private void jbtn_atualizarPetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_atualizarPetMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_atualizarPetMouseMoved

    private void jbtn_atualizarPetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_atualizarPetMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_atualizarPetMouseExited

    private void jbtn_atualizarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atualizarPetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtn_atualizarPetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_atualizar_pet().setVisible(true);
            }
        });
    }
    
    private void initMenuPanel() {
        MenuPanel menuPanel = new MenuPanel();
        jPanel_menu.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtF_cor;
    private javax.swing.JTextField JTxtF_nome_dono;
    private javax.swing.JTextField JTxtF_nome_pet;
    private javax.swing.JTextField JTxtF_raca;
    private javax.swing.JCheckBox chkBx_Nao;
    private javax.swing.JCheckBox chkBx_Sim;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JButton jbtn_AddVacinas;
    private javax.swing.JButton jbtn_atualizarPet;
    private javax.swing.JComboBox<Porte> jcmbBx_Porte;
    private javax.swing.JComboBox<Sexo> jcmbBx_sexo;
    private javax.swing.JLabel jlbl_atualizar_pet;
    private javax.swing.JLabel jlbl_background;
    private javax.swing.JLabel jlbl_castrado;
    private javax.swing.JLabel jlbl_cor;
    private javax.swing.JLabel jlbl_nome_dono;
    private javax.swing.JLabel jlbl_nome_pet;
    private javax.swing.JLabel jlbl_porte;
    private javax.swing.JLabel jlbl_raca;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JLabel jllb_vacinas;
    private javax.swing.JPanel jpanel_atualizar_pet;
    private javax.swing.JLabel jtextArea_compor_pet;
    private javax.swing.JLabel jtextArea_saude_pet;
    private javax.swing.JScrollPane jtxtArea_Comportamento;
    private javax.swing.JScrollPane jtxtArea_Saude;
    private javax.swing.JTextArea jtxtarea_comportamento;
    private javax.swing.JTextArea jtxtarea_saude;
    // End of variables declaration//GEN-END:variables
}
