/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.mycompany.petagenda.MenuPanel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import ui.custom.RoundedCornerBorder;
import ui.custom.RoundedCornerButtonUI;

/**
 *
 * @author kevin
 */

public class Tela_visualizacao_pet extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro_funcionario
     */
    public Tela_visualizacao_pet() {
        initComponents();
        initMenuPanel();
        jPanel_deletar.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        jPanel_editar.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel_menu = new javax.swing.JPanel();
        jbtn_cadastrarPet = new javax.swing.JButton();
        jPanel_tabela_pet = new javax.swing.JPanel();
        jScrollPane_tabela_visualizacao_pet = new javax.swing.JScrollPane();
        jtbl_visualizacao_pet = new javax.swing.JTable();
        jPanel_deletar = new javax.swing.JPanel();
        jlbl_deletar = new javax.swing.JLabel();
        jPanel_editar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Merriweather", 0, 45)); // NOI18N
        jLabel1.setText("Pets");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jPanel_menu.setBackground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setForeground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jPanel_menu.setMinimumSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));

        jbtn_cadastrarPet.setBackground(new java.awt.Color(77, 120, 63));
        jbtn_cadastrarPet.setFont(new java.awt.Font("Merriweather", 0, 20)); // NOI18N
        jbtn_cadastrarPet.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_cadastrarPet.setText("Cadastrar Pet");
        jbtn_cadastrarPet.setBorder(null);
        jbtn_cadastrarPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_cadastrarPet.setPreferredSize(new java.awt.Dimension(240, 50));
        jbtn_cadastrarPet.setUI(new RoundedCornerButtonUI());
        jbtn_cadastrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cadastrarPetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_cadastrarPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, -1, -1));

        jPanel_tabela_pet.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_tabela_pet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel_tabela_pet.setMinimumSize(new java.awt.Dimension(905, 560));
        jPanel_tabela_pet.setOpaque(false);
        jPanel_tabela_pet.setPreferredSize(new java.awt.Dimension(815, 480));
        jPanel_tabela_pet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane_tabela_visualizacao_pet.setPreferredSize(new java.awt.Dimension(815, 480));

        jtbl_visualizacao_pet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome do pet", "Raça", "Cor", "Porte", "Sexo", "Castrado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane_tabela_visualizacao_pet.setViewportView(jtbl_visualizacao_pet);

        jPanel_tabela_pet.add(jScrollPane_tabela_visualizacao_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel_tabela_pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 106, -1, -1));

        jPanel_deletar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_deletar.setPreferredSize(new java.awt.Dimension(42, 42));
        jPanel_deletar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon deletar.png"))); // NOI18N
        jPanel_deletar.add(jlbl_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        getContentPane().add(jPanel_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1216, 533, -1, -1));

        jPanel_editar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_editar.setPreferredSize(new java.awt.Dimension(42, 42));
        jPanel_editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon editar.png"))); // NOI18N
        jPanel_editar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        getContentPane().add(jPanel_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1258, 533, -1, -1));

        jlbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_PADRAO.png"))); // NOI18N
        jlbl_background.setText(" ");
        jlbl_background.setMaximumSize(new java.awt.Dimension(1366, 768));
        jlbl_background.setMinimumSize(new java.awt.Dimension(1366, 768));
        jlbl_background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jlbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cadastrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cadastrarPetActionPerformed
        // TODO add your handling code here:
        tela_cadastro_pet telaCadPets = new tela_cadastro_pet();
        telaCadPets.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_cadastrarPetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        PopularTabela("SELECT nome, raca, cor, porte, sexo, e_castrado FROM pet");
    }//GEN-LAST:event_formWindowOpened
    private void initMenuPanel() {
        MenuPanel menuPanel = new MenuPanel();
        jPanel_menu.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));
    }
    public void PopularTabela(String sql){
        try {
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/petagenda","root","");
            PreparedStatement banco = (PreparedStatement)con.prepareStatement(sql);
            banco.execute();
            
            ResultSet resultado = banco.executeQuery(sql);
            
            DefaultTableModel model =(DefaultTableModel)jtbl_visualizacao_pet.getModel();
            model.setNumRows(0);
            
            while(resultado.next()){
                model.addRow(new Object[]
                {
                   resultado.getString("nome"),
                   resultado.getString("raca"),
                   resultado.getString("cor"),
                   resultado.getString("porte"),
                   resultado.getString("sexo"),
                   resultado.getString("e_castrado")
                });
            }
            banco.close();
            con.close();
        }catch (SQLException e){
            System.out.println("o erro foi:"+e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Tela_visualizacao_pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Tela_visualizacao_pet().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_deletar;
    private javax.swing.JPanel jPanel_editar;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_tabela_pet;
    private javax.swing.JScrollPane jScrollPane_tabela_visualizacao_pet;
    private javax.swing.JButton jbtn_cadastrarPet;
    private javax.swing.JLabel jlbl_background;
    private javax.swing.JLabel jlbl_deletar;
    private javax.swing.JTable jtbl_visualizacao_pet;
    // End of variables declaration//GEN-END:variables

}
