/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.mycompany.petagenda.MenuPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import petagenda.bd.BD;
import ui.custom.RoundedCornerButtonUI;

/**
 *
 * @author kevin
 */
public class Tela_visualizacao_historico_servicos extends javax.swing.JFrame {

    /**
     * Creates new form Tela_visualizacao_historico_servicos
     */
    public void PopularTabela (String sql){
        try {
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/pet_agenda","root","");
            PreparedStatement banco = (PreparedStatement)con.prepareStatement(sql);
            banco.execute();
            
            ResultSet resultado = banco.executeQuery(sql);
            
            DefaultTableModel model =(DefaultTableModel)jtbl_historico_servico.getModel();
            model.setNumRows(0);
            
            while(resultado.next()){
                model.addRow(new Object[]
                {
                    //Criar a view para preencher a tabela do sistema
                   resultado.getString("id"),
                   resultado.getString("nome"),
                   resultado.getString("cpf")
                });
            }
            banco.close();
            con.close();
        }catch (SQLException e){
            System.out.println("o erro foi:"+e);
        }

    }
    public Tela_visualizacao_historico_servicos() {
        initComponents();
        initMenuPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_historico_servicos = new javax.swing.JLabel();
        jPanel_tabela = new javax.swing.JPanel();
        jScrollPane_historico_servico = new javax.swing.JScrollPane();
        jtbl_historico_servico = new javax.swing.JTable();
        jbtn_cadastrarIncidente = new javax.swing.JButton();
        jPanel_menu = new javax.swing.JPanel();
        jlbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_historico_servicos.setBackground(new java.awt.Color(255, 255, 255));
        lbl_historico_servicos.setFont(new java.awt.Font("Merriweather", 0, 45)); // NOI18N
        lbl_historico_servicos.setText("Histórico de Serviços");
        getContentPane().add(lbl_historico_servicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jPanel_tabela.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_tabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel_tabela.setMinimumSize(new java.awt.Dimension(905, 560));
        jPanel_tabela.setOpaque(false);
        jPanel_tabela.setPreferredSize(new java.awt.Dimension(865, 480));
        jPanel_tabela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane_historico_servico.setPreferredSize(new java.awt.Dimension(865, 480));

        jtbl_historico_servico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Agendamento", "Pets", "Nome do funcionário", "Data", "Horário", "Serviço prestado", "Incidentes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbl_historico_servico.setPreferredSize(new java.awt.Dimension(865, 480));
        jtbl_historico_servico.getTableHeader().setReorderingAllowed(false);
        jtbl_historico_servico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_historico_servicoMouseClicked(evt);
            }
        });
        jScrollPane_historico_servico.setViewportView(jtbl_historico_servico);

        jPanel_tabela.add(jScrollPane_historico_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        getContentPane().add(jPanel_tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 103, -1, -1));

        jbtn_cadastrarIncidente.setBackground(new java.awt.Color(77, 120, 63));
        jbtn_cadastrarIncidente.setFont(new java.awt.Font("Merriweather", 0, 20)); // NOI18N
        jbtn_cadastrarIncidente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_cadastrarIncidente.setText("Cadastrar Incidente");
        jbtn_cadastrarIncidente.setBorder(null);
        jbtn_cadastrarIncidente.setPreferredSize(new java.awt.Dimension(240, 50));
        jbtn_cadastrarIncidente.setUI(new RoundedCornerButtonUI());
        jbtn_cadastrarIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cadastrarIncidenteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_cadastrarIncidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 620, -1, -1));

        jPanel_menu.setBackground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setForeground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setAlignmentX(0.0F);
        jPanel_menu.setAlignmentY(0.0F);
        jPanel_menu.setPreferredSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jlbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_PADRAO.png"))); // NOI18N
        getContentPane().add(jlbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cadastrarIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cadastrarIncidenteActionPerformed
        // TODO add your handling code here:
        Tela_incidentes incidente = new Tela_incidentes();
        incidente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_cadastrarIncidenteActionPerformed

    private void jtbl_historico_servicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_historico_servicoMouseClicked
        // TODO add your handling code here:
        int col = jtbl_historico_servico.getSelectedColumn();
        int row = jtbl_historico_servico.getSelectedRow();
        Object valor = jtbl_historico_servico.getValueAt(row, col);
        Tela_incidentes frame = new Tela_incidentes();
        String data = "";
        String descricao = "";
        String emergencia = "";
        String nome = "";
        
        if (col == 6) {
            Object IdAgendamento = jtbl_historico_servico.getValueAt(row,(col-6));
            if (valor.equals("Houve")) {
                try {
                    Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/pet_agenda","root","");
                    String sql = "SELECT i.data_hora, i.descricao, i.e_emergencia, p.nome FROM incidente AS i INNER JOIN pet AS p i.id_pet = p.id_pet WHERE i.id_agendamento ="+IdAgendamento;
                    PreparedStatement banco = (PreparedStatement)con.prepareStatement(sql);
                    banco.execute();
            
                    ResultSet resultado = banco.executeQuery(sql);
                    
                    while (resultado.next()) {
                        data = resultado.getString("i.data_hora");
                        descricao = resultado.getString("i.descricao");
                        emergencia = resultado.getString("i.e_emergencia");
                        nome = resultado.getString("p.nome");
                    }
                    
                    JOptionPane.showMessageDialog(null,"Nome:"+nome+"\nData:"+data+"\nEmergência Médica:"+emergencia+"\nDescrição:"+descricao, "Incidente",JOptionPane.INFORMATION_MESSAGE);
                    
                }catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "ERRO:"+e.getMessage());
                }
            } else if (valor.equals("Não houve")) {
                JOptionPane.showMessageDialog(null, "Não houve incidente nesse serviço.");
            } else{
                JOptionPane.showMessageDialog(null, "Não existe nada dentro dessa linha.");
            }
        }
    }//GEN-LAST:event_jtbl_historico_servicoMouseClicked
    
    private void initMenuPanel() {
        MenuPanel menuPanel = new MenuPanel();
        jPanel_menu.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));
    }
    
    private void carregarDadosTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jtbl_historico_servico.getModel();
        modelo.setRowCount(0);
        
        String sql = "";
        
        /*
        try (Connection conn = BD.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery()) {
            
            while (rs.next()) {
                Object[] linha = {
                    rs.getString("pets"),
                    rs.getString("nome"),
                    rs.getString("data"),
                    rs.getString("horario"),
                    rs.getString("servico"),
                    rs.getString("incidentes"),
                };
                
            }
            
        }
        */
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_historico_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_historico_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_historico_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_visualizacao_historico_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_visualizacao_historico_servicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_tabela;
    private javax.swing.JScrollPane jScrollPane_historico_servico;
    private javax.swing.JButton jbtn_cadastrarIncidente;
    private javax.swing.JLabel jlbl_background;
    private javax.swing.JTable jtbl_historico_servico;
    private javax.swing.JLabel lbl_historico_servicos;
    // End of variables declaration//GEN-END:variables
}
