/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.mycompany.petagenda.MenuPanel;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import petagenda.Cliente;
import petagenda.bd.BD;
import ui.custom.RoundedCornerButtonUI;

/**
 *
 * @author kevin
 */
public class tela_atualizar_cliente extends javax.swing.JFrame {

    /**
     * Creates new form tela_atualizar_cliente
     */
    public tela_atualizar_cliente() {
        initComponents();
        initMenuPanel();
        AlinhaJField();
        carregar_tela();
    }
    
    private void AlinhaJField() {
        Border line = BorderFactory.createLineBorder(Color.BLACK, 2);
        Border empty = new EmptyBorder(0, 5, 0, 0);
        CompoundBorder border = new CompoundBorder(line, empty);

        jtxtf_campo_nome_cliente.setBorder(border);
        jtxtf_campo_cpf.setBorder(border);
        jtxtf_campo_telefone.setBorder(border);
        jcbox_Selecao_servico.setBorder(border);
        jtxtf_campo_cep.setBorder(border);
        jtxtf_campo_num.setBorder(border);
        jtxtf_campo_rua.setBorder(border);
        jtxtf_campo_bairro.setBorder(border);
        jtxtf_campo_cidade.setBorder(border);
    }
    
    // Limpa as informações dos campos de Usuario
    private void clearFieldsInfo() {
        jtxtf_campo_nome_cliente.setText(null);
        jtxtf_campo_cpf.setText(null);
        jtxtf_campo_telefone.setText(null);
        jcbox_Selecao_servico.setSelectedItem(0);
        jtxtf_campo_cep.setText(null);
        jtxtf_campo_num.setText(null);
        jtxtf_campo_rua.setText(null);
        jtxtf_campo_bairro.setText(null);
        jtxtf_campo_cidade.setText(null);
    }
    
    private void carregar_tela() {
        Cliente cliente = BD.Cliente.selectById(Tela_visualizacao_cliente.id_cliente);
        
        jtxtf_campo_nome_cliente.setText(cliente.getNome());
        jtxtf_campo_cpf.setText(cliente.getCpf().toString());
        jtxtf_campo_telefone.setText(cliente.getTelefone());
        //Serviço contratado está faltando.
        jtxtf_campo_cep.setText(cliente.getCep());
        jtxtf_campo_num.setText(cliente.getNumero());
        jtxtf_campo_rua.setText(cliente.getRua());
        jtxtf_campo_bairro.setText(cliente.getBairro());
        jtxtf_campo_cidade.setText(cliente.getCidade());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_atualizar_cliente = new javax.swing.JPanel();
        jlbl_titulo = new javax.swing.JLabel();
        jlbl_nome_cliente = new javax.swing.JLabel();
        jtxtf_campo_nome_cliente = new javax.swing.JTextField();
        jlbl_cpf = new javax.swing.JLabel();
        jtxtf_campo_cpf = new javax.swing.JTextField();
        jlbl_telefone = new javax.swing.JLabel();
        jtxtf_campo_telefone = new javax.swing.JTextField();
        jlbl_servico_contratado = new javax.swing.JLabel();
        jcbox_Selecao_servico = new javax.swing.JComboBox();
        jlbl_cep = new javax.swing.JLabel();
        jtxtf_campo_cep = new javax.swing.JTextField();
        jlbl_num = new javax.swing.JLabel();
        jtxtf_campo_num = new javax.swing.JTextField();
        jlbl_rua = new javax.swing.JLabel();
        jtxtf_campo_rua = new javax.swing.JTextField();
        jlbl_bairro = new javax.swing.JLabel();
        jtxtf_campo_bairro = new javax.swing.JTextField();
        jlbl_cidade = new javax.swing.JLabel();
        jtxtf_campo_cidade = new javax.swing.JTextField();
        jbtn_Cadastrar_cliente = new javax.swing.JButton();
        jPanel_menu = new javax.swing.JPanel();
        jlbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_atualizar_cliente.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_atualizar_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel_atualizar_cliente.setPreferredSize(new java.awt.Dimension(630, 640));
        jPanel_atualizar_cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_titulo.setBackground(new java.awt.Color(0, 0, 0));
        jlbl_titulo.setFont(new java.awt.Font("Merriweather", 0, 45)); // NOI18N
        jlbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_titulo.setText("Atualizar cliente");
        jlbl_titulo.setMaximumSize(new java.awt.Dimension(380, 45));
        jlbl_titulo.setMinimumSize(new java.awt.Dimension(380, 45));
        jlbl_titulo.setPreferredSize(new java.awt.Dimension(380, 45));
        jPanel_atualizar_cliente.add(jlbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jlbl_nome_cliente.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_nome_cliente.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_nome_cliente.setText("Nome completo do cliente:");
        jlbl_nome_cliente.setMaximumSize(new java.awt.Dimension(180, 20));
        jlbl_nome_cliente.setMinimumSize(new java.awt.Dimension(180, 20));
        jlbl_nome_cliente.setPreferredSize(new java.awt.Dimension(180, 20));
        jPanel_atualizar_cliente.add(jlbl_nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 85, 180, 20));

        jtxtf_campo_nome_cliente.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_nome_cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_nome_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtf_campo_nome_cliente.setMinimumSize(new java.awt.Dimension(550, 50));
        jtxtf_campo_nome_cliente.setPreferredSize(new java.awt.Dimension(550, 50));
        jPanel_atualizar_cliente.add(jtxtf_campo_nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 106, -1, -1));

        jlbl_cpf.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_cpf.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cpf.setText("CPF:");
        jPanel_atualizar_cliente.add(jlbl_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 176, -1, -1));

        jtxtf_campo_cpf.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtf_campo_cpf.setMinimumSize(new java.awt.Dimension(250, 50));
        jtxtf_campo_cpf.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel_atualizar_cliente.add(jtxtf_campo_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 195, -1, -1));

        jlbl_telefone.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_telefone.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_telefone.setText("Telefone:");
        jPanel_atualizar_cliente.add(jlbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 176, -1, -1));

        jtxtf_campo_telefone.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtf_campo_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_campo_telefoneActionPerformed(evt);
            }
        });
        jPanel_atualizar_cliente.add(jtxtf_campo_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 195, 270, 50));

        jlbl_servico_contratado.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_servico_contratado.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_servico_contratado.setText("Serviço contratado:");
        jlbl_servico_contratado.setMaximumSize(new java.awt.Dimension(150, 15));
        jlbl_servico_contratado.setMinimumSize(new java.awt.Dimension(150, 15));
        jlbl_servico_contratado.setPreferredSize(new java.awt.Dimension(130, 15));
        jPanel_atualizar_cliente.add(jlbl_servico_contratado, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 265, -1, -1));

        jcbox_Selecao_servico.setBackground(new java.awt.Color(217, 217, 217));
        jcbox_Selecao_servico.setFont(new java.awt.Font("Merriweather", 0, 14)); // NOI18N
        jcbox_Selecao_servico.setForeground(new java.awt.Color(217, 217, 217));
        jcbox_Selecao_servico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcbox_Selecao_servico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbox_Selecao_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_Selecao_servicoActionPerformed(evt);
            }
        });
        jPanel_atualizar_cliente.add(jcbox_Selecao_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 284, 250, 50));

        jlbl_cep.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_cep.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cep.setText("CEP:");
        jPanel_atualizar_cliente.add(jlbl_cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 265, -1, -1));

        jtxtf_campo_cep.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_cep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_cep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtf_campo_cep.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel_atualizar_cliente.add(jtxtf_campo_cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 284, 150, 50));

        jlbl_num.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_num.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_num.setText("N°");
        jPanel_atualizar_cliente.add(jlbl_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 265, -1, -1));

        jtxtf_campo_num.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_num.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel_atualizar_cliente.add(jtxtf_campo_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 284, 90, 50));

        jlbl_rua.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_rua.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_rua.setText("Rua:");
        jPanel_atualizar_cliente.add(jlbl_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 354, -1, -1));

        jtxtf_campo_rua.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_rua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel_atualizar_cliente.add(jtxtf_campo_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 373, 550, 50));

        jlbl_bairro.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_bairro.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_bairro.setText("Bairro:");
        jlbl_bairro.setPreferredSize(new java.awt.Dimension(52, 15));
        jPanel_atualizar_cliente.add(jlbl_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 443, 50, -1));

        jtxtf_campo_bairro.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_bairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_bairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel_atualizar_cliente.add(jtxtf_campo_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 462, 270, 50));

        jlbl_cidade.setFont(new java.awt.Font("Merriweather", 0, 15)); // NOI18N
        jlbl_cidade.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cidade.setText("Cidade:");
        jlbl_cidade.setPreferredSize(new java.awt.Dimension(56, 15));
        jPanel_atualizar_cliente.add(jlbl_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 443, -1, -1));

        jtxtf_campo_cidade.setBackground(new java.awt.Color(217, 217, 217));
        jtxtf_campo_cidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtf_campo_cidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtf_campo_cidade.setPreferredSize(new java.awt.Dimension(300, 60));
        jPanel_atualizar_cliente.add(jtxtf_campo_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 462, 250, 50));

        jbtn_Cadastrar_cliente.setBackground(new java.awt.Color(77, 120, 63));
        jbtn_Cadastrar_cliente.setFont(new java.awt.Font("Merriweather", 0, 20)); // NOI18N
        jbtn_Cadastrar_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Cadastrar_cliente.setText("ATUALIZAR");
        jbtn_Cadastrar_cliente.setBorder(null);
        jbtn_Cadastrar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Cadastrar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Cadastrar_clienteActionPerformed(evt);
            }
        });
        // Aplicando a UI personalizada
        jbtn_Cadastrar_cliente.setUI(new RoundedCornerButtonUI());
        jPanel_atualizar_cliente.add(jbtn_Cadastrar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 557, 240, 50));

        getContentPane().add(jPanel_atualizar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 40, -1, -1));

        jPanel_menu.setBackground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setForeground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jPanel_menu.setMinimumSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));

        jlbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_PADRAO.png"))); // NOI18N
        getContentPane().add(jlbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtf_campo_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_campo_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_campo_telefoneActionPerformed

    private void jcbox_Selecao_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_Selecao_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbox_Selecao_servicoActionPerformed

    private void jbtn_Cadastrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Cadastrar_clienteActionPerformed
        // TODO add your handling code here:
        /*
        Cliente cadastrar = null;
        Cliente_servico cadastro_contratado = null;

        boolean duplicado = false;

        // Cadastro do cliente.
        try {
            cadastrar = getFieldInfo(); // Retornara null se informações não forem válidas.
        }
        catch (SQLException ex) {
            Logger.getLogger(Tela_cadastro_cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        String strCpf = cadastrar.getCpf().toString();
        duplicado = Duplicado(strCpf);

        if (duplicado == false) {
            if (cadastrar != null) {
                int cl = BD.Cliente.insert(cadastrar); // Dando insert no cliente.

                // cliente_contrata_servico.
                cadastro_contratado = getClienteServico();
                int cc = BD.ClienteContrataServico.insert(cadastro_contratado);

                if (cl > 0 && cc > 0) { // Foi cadastrado cliente e cliente_contrata_servico.
                    clearFieldsInfo();
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "CPF já cadastrado.", "CPF inválido", JOptionPane.ERROR_MESSAGE);
        }
        */
    }//GEN-LAST:event_jbtn_Cadastrar_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_atualizar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_atualizar_cliente().setVisible(true);
            }
        });
    }
    
    private void initMenuPanel() {
        MenuPanel menuPanel = new MenuPanel();
        jPanel_menu.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_atualizar_cliente;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JButton jbtn_Cadastrar_cliente;
    private javax.swing.JComboBox jcbox_Selecao_servico;
    private javax.swing.JLabel jlbl_background;
    private javax.swing.JLabel jlbl_bairro;
    private javax.swing.JLabel jlbl_cep;
    private javax.swing.JLabel jlbl_cidade;
    private javax.swing.JLabel jlbl_cpf;
    private javax.swing.JLabel jlbl_nome_cliente;
    private javax.swing.JLabel jlbl_num;
    private javax.swing.JLabel jlbl_rua;
    private javax.swing.JLabel jlbl_servico_contratado;
    private javax.swing.JLabel jlbl_telefone;
    private javax.swing.JLabel jlbl_titulo;
    private javax.swing.JTextField jtxtf_campo_bairro;
    private javax.swing.JTextField jtxtf_campo_cep;
    private javax.swing.JTextField jtxtf_campo_cidade;
    private javax.swing.JTextField jtxtf_campo_cpf;
    private javax.swing.JTextField jtxtf_campo_nome_cliente;
    private javax.swing.JTextField jtxtf_campo_num;
    private javax.swing.JTextField jtxtf_campo_rua;
    private javax.swing.JTextField jtxtf_campo_telefone;
    // End of variables declaration//GEN-END:variables
}
