/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.mycompany.petagenda.MenuPanel;
import java.awt.Dimension;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import petagenda.bd.BD;
import ui.custom.RoundedCornerBorder;
import ui.custom.RoundedCornerButtonUI;
import ui.custom.RoundedCornerButtonUI;

/**
 *
 * @author Nata e Julia
 */
public class Tela_servicos extends javax.swing.JFrame {

    /**
     * Creates new form Tela_config
     */
    public Tela_servicos() {
        initComponents();
        initMenuPanel();
        carregarDadosTabela();
        AjustarColuna();
    }
    
    // Personaliza a "width" da coluna em geral.
    private void AjustarColuna() {
        // Centraliza a coluna.
        DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
        rendererCentro.setHorizontalAlignment(SwingConstants.CENTER);
        
        // Alinha a coluna a direita.
        DefaultTableCellRenderer rendererDireita = new DefaultTableCellRenderer();  
        rendererDireita.setHorizontalAlignment(SwingConstants.RIGHT);
        
        // Alinha a coluna a esquerda.
        DefaultTableCellRenderer rendererEsquerda = new DefaultTableCellRenderer();  
        rendererEsquerda.setHorizontalAlignment(SwingConstants.LEFT);  

        // Define o tamanho do cabeçalho.
        JTableHeader header = tbl_Servicos.getTableHeader();  
        header.setPreferredSize(new Dimension(0, 30));
        TableColumnModel modeloDaColuna = tbl_Servicos.getColumnModel();  

        // Organiza a tabela de acordo com os parametros.
        modeloDaColuna.getColumn(0).setCellRenderer(rendererEsquerda); // Pet
        modeloDaColuna.getColumn(1).setCellRenderer(rendererEsquerda); // Nome do funcionário
        modeloDaColuna.getColumn(2).setCellRenderer(rendererCentro); // Data
        modeloDaColuna.getColumn(3).setCellRenderer(rendererCentro); // Horário
        modeloDaColuna.getColumn(4).setCellRenderer(rendererEsquerda); // Serviço prestado
        modeloDaColuna.getColumn(5).setCellRenderer(rendererEsquerda); // Incidente

        // Define o tamanho das colunas na tabela.
        modeloDaColuna.getColumn(0).setPreferredWidth(370); // Pet
        modeloDaColuna.getColumn(1).setPreferredWidth(370); // Nome do funcionário
        modeloDaColuna.getColumn(2).setPreferredWidth(120); // Data
        modeloDaColuna.getColumn(3).setPreferredWidth(100); // Horário
        modeloDaColuna.getColumn(4).setPreferredWidth(120); // Serviço prestado
        modeloDaColuna.getColumn(5).setPreferredWidth(200); // Incidente  
    }

    private void moveHeader() {
        // Cabeçalho da tabela e o JScrollPane
        JTableHeader header = tbl_Servicos.getTableHeader();
        JScrollBar horizontalScrollBar = jScroll_tabela.getHorizontalScrollBar();

        // Sincroniza a rolagem da JTable com o header
        horizontalScrollBar.addAdjustmentListener(new AdjustmentListener() {
            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
                header.setLocation(-e.getValue(), header.getY());
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_menu = new javax.swing.JPanel();
        jPanel_tabela = new javax.swing.JPanel();
        jScroll_tabela = new javax.swing.JScrollPane();
        tbl_Servicos = new javax.swing.JTable();
        lbl_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_menu.setBackground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setForeground(new java.awt.Color(124, 115, 101));
        jPanel_menu.setFont(new java.awt.Font("Merriweather", 0, 12)); // NOI18N
        jPanel_menu.setMinimumSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(205, 768));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));

        jPanel_tabela.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_tabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel_tabela.setMinimumSize(new java.awt.Dimension(905, 560));
        jPanel_tabela.setOpaque(false);
        jPanel_tabela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll_tabela.setPreferredSize(new java.awt.Dimension(915, 480));
        jScroll_tabela.setVerifyInputWhenFocusTarget(false);

        tbl_Servicos.setFont(new java.awt.Font("Merriweather", 0, 16)); // NOI18N
        tbl_Servicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pet", "Nome do funcionário", "Data", "Horário", "Serviço prestado", "Incidente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Servicos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbl_Servicos.setPreferredSize(new java.awt.Dimension(1280, 480));
        tbl_Servicos.setRowHeight(30);
        tbl_Servicos.setShowHorizontalLines(true);
        tbl_Servicos.setShowVerticalLines(true);
        tbl_Servicos.getTableHeader().setReorderingAllowed(false);
        jScroll_tabela.setViewportView(tbl_Servicos);
        if (tbl_Servicos.getColumnModel().getColumnCount() > 0) {
            tbl_Servicos.getColumnModel().getColumn(0).setResizable(false);
            tbl_Servicos.getColumnModel().getColumn(1).setResizable(false);
            tbl_Servicos.getColumnModel().getColumn(2).setResizable(false);
            tbl_Servicos.getColumnModel().getColumn(3).setResizable(false);
            tbl_Servicos.getColumnModel().getColumn(4).setResizable(false);
            tbl_Servicos.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel_tabela.add(jScroll_tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel_tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 103, -1, -1));

        lbl_title.setFont(new java.awt.Font("Merriweather", 0, 45)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(0, 0, 0));
        lbl_title.setText("Histórico de Serviços");
        lbl_title.setPreferredSize(new java.awt.Dimension(680, 50));
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG_PADRAO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void initMenuPanel() {
        MenuPanel menuPanel = new MenuPanel();
        jPanel_menu.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 768));
    }

    private void carregarDadosTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tbl_Servicos.getModel();
        modelo.setRowCount(0);

        String sql = "SELECT * FROM vw_detalhes_servico";

        try (Connection conn = BD.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            DefaultTableModel model = new DefaultTableModel(new String[]{"Pet", "Nome do Funcionário", "Data", "Horário", "Serviço Prestado", "Incidente"}, 0);

            while (rs.next()) {
                String pet = rs.getString("Pet");
                String nomeFuncionario = rs.getString("NomeFuncionario");
                String data = rs.getString("Data");
                String horario = rs.getString("Horario");
                String servicoPrestado = rs.getString("ServicoPrestado");
                String incidente = rs.getString("Incidente");

                model.addRow(new Object[]{pet, nomeFuncionario, data, horario, servicoPrestado, incidente});
            }
            
            tbl_Servicos.setModel(model);
            
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_servicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_tabela;
    private javax.swing.JScrollPane jScroll_tabela;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTable tbl_Servicos;
    // End of variables declaration//GEN-END:variables
}
